MATAD02 - Products migration
riessgroup/matador-magento-migration pull request #7
Opened 2024-08-09 12:38 UTC by ivancosmin

### What does this PR change? 
Please delete these lines and write about what feature, enhancement, or bug this pull request solves. It would help if you were specific so the PR reviewer understands the reviewed code. 

### Relevant Task Links 
- Asana Link 1
- Asana Link 2
... 
### Please check the following boxes. 
- [ ] I have tested my code, and my tests passed.
- [ ] If the repository has tests, I've ensured I wrote tests for my code and all existing tests pass.
- [ ] **I wrote all relevant feature documentation, or I made all required changes to documentation in README.md or the repository Wiki.**

2024-08-09 16:13 UTC, radmen requested changes
I have finished reviewing your Pull Request. I have flagged my comments with the following emojis:

- 🔴 indicates that changes are required
- 🔵 suggests making a change
- 💬 is a tip, general feedback, or a comment
- 🤔 is a question
  
Please review my comments and make the necessary changes. If I left any code suggestions, they might not work. Check them first before making any commits. 

If you have any questions or concerns, please let me know.

2024-08-09 16:13 UTC, radmen commented on database/migrations/2024_08_08_074903_add_sku_on_products_table.php
> +        });
:red_circle: This doesn't make sense. There are still simple products that are not variants. They have SKU that should be preserved.

2024-08-09 16:13 UTC, radmen commented on app/helpers.php
> +        dd(SyncError::fromString($error->getResponse()->getBody()));
:red_circle: This should be removed

2024-08-19 06:50 UTC, ivancosmin commented on app/Adapters/MagentoAdapter.php
> +                    yield $response;
reverted

2024-08-19 06:51 UTC, ivancosmin commented on app/Console/Commands/PullProducts.php
> +                        'sku' => $item->sku
i dropped sku. it was in first iteresetion when i needed to use it to filter

2024-08-19 06:59 UTC, ivancosmin commented on app/Console/Commands/PullProducts.php
> -                        'origin_options' => $this->magentoAdapter->getProductOptions($item->sku),
after the switch for grouped products, magento responded on this api call with "Unavailable for this type of products"

2024-08-19 06:59 UTC, ivancosmin commented on app/Console/Commands/PullProducts.php
> +                                'sku' => $product->sku
dropped right now

2024-08-19 07:00 UTC, ivancosmin commented on app/Console/Commands/PushProducts.php
> +//                    });
it was for debug, in first days

2024-08-19 07:00 UTC, ivancosmin commented on app/Console/Commands/PushProducts.php
> +//            dd($data);
removed. it was for debug, in first days

2024-08-19 07:01 UTC, ivancosmin commented on app/Transformers/ProductTransformer.php
> +
from slack discussion i understood that we need to skip products without variants. i just add this for double check

2024-08-19 07:01 UTC, ivancosmin commented on database/migrations/2024_08_08_074903_add_sku_on_products_table.php
> +        });
sku dropped

2024-08-19 07:01 UTC, ivancosmin commented on app/helpers.php
> +        dd(SyncError::fromString($error->getResponse()->getBody()));
removed. it was for debug, in first days

2024-08-19 08:08 UTC, radmen requested changes

2024-08-19 08:08 UTC, radmen commented on app/Transformers/ProductTransformer.php
> +        if (!in_array(MigrationProduct::MATADOR_WEBSITE_ID, $data['extension_attributes']['website_ids'], true)) {
:large_blue_circle: If possible, I recommend using named arguments to avoid the [boolean trap](https://ariya.io/2011/08/hall-of-api-shame-boolean-trap).

```suggestion
        if (!in_array(MigrationProduct::MATADOR_WEBSITE_ID, $data['extension_attributes']['website_ids'], strict: true)) {
```

2024-08-19 08:08 UTC, radmen commented on app/Transformers/ProductTransformer.php
> +        return true;
:large_blue_circle: this could be reduced to simpler conditions with early returns:

```suggestion
        if ($data['status'] != 2) {
            return false;
        }
        
        $hasEnabledVariants = collect($variants)
            ->some(fn ($item) => $item->origin_data['status'] === 1);
            
        return $hasEnabledVariants;
```

2024-08-19 08:29 UTC, ivancosmin commented on app/Adapters/MagentoAdapter.php
> +        )->first();
thanks, i will update it

2024-08-19 08:33 UTC, ivancosmin commented on app/Transformers/ProductTransformer.php
> +        return true;
we can't reject unactive grouped products because we can import them with active variants. in magento we can have grouped products disabled, but with active variants

2024-08-19 08:35 UTC, ivancosmin commented on app/Adapters/MagentoAdapter.php
> +                    yield $response;
it is the initial code, it is not mine. we need michal here

2024-08-19 08:37 UTC, radmen commented on app/Adapters/MagentoAdapter.php
> +                    yield $response;
@michalkuchtapl could you help here?

2024-08-19 08:38 UTC, radmen commented on app/Transformers/ProductTransformer.php
> +        return true;
hmm, in that case, the logic you currently have is not working correctly. It will reject all grouped products that don't have any enabled variants.

2024-08-19 08:40 UTC, ivancosmin commented on app/Transformers/ProductTransformer.php
> +        return true;
we can reconfirm with Hollie, but I understood that we don't migrate products without variants (or with disabled variants)

2024-08-19 08:49 UTC, radmen commented on app/Transformers/ProductTransformer.php
> +        return true;
Ok, I think I see the issue here. It's even more important to write it in a more readable way :)

```suggestion
        if ($data['status'] !== 2) {
            return true;
        }
        
        return collect($variants)
            ->some(fn ($item) => $item->origin_data['status'] === 1);
```

Does it make any sense?

2024-08-19 08:50 UTC, ivancosmin commented on app/Transformers/ProductTransformer.php
> +        return true;
ok, i will update

2024-08-22 12:21 UTC, radmen approved these changes

2024-08-22 12:21 UTC, radmen commented on app/Adapters/MagentoAdapter.php
> +        $existingEntry = cache()->get($cacheId($labelKey));
:large_blue_circle: I think here it would be better to use `has()` instead. It makes the code a little bit more consistent and avoids the double retrieval of the same cache value.

```suggestion
        $existingEntry = cache()->has($cacheId($labelKey));
```

2024-08-22 12:21 UTC, radmen commented on app/Console/Commands/PushProductsMetafields.php
> +                $migrationOriginData = $product->migrationProduct()->value('origin_data');
:large_blue_circle: `migrationProduct()` should be lazy loaded using `with()`. Otherwise, the iteration process will be slower, just because it requires fetching the product separately for each item.

2024-08-23 09:38 UTC, merged