MATAD02 - Product-Artist association
riessgroup/matador-magento-migration pull request #9
Opened 2024-08-26 18:31 UTC by ivancosmin

### What does this PR change? 
Product - Artist association

Identify artist metaobject and associate it with the product

2024-08-27 16:34 UTC, radmen requested changes
I have finished reviewing your Pull Request. I have flagged my comments with the following emojis:

- 🔴 indicates that changes are required
- 🔵 suggests making a change
- 💬 is a tip, general feedback, or a comment
- 🤔 is a question
  
Please review my comments and make the necessary changes. If I left any code suggestions, they might not work. Check them first before making any commits. 

If you have any questions or concerns, please let me know.

2024-08-27 16:34 UTC, radmen commented on app/Console/Commands/ProductsArtistsSync.php
> +                        $artist = $this->shopifyAdapter->getArtistMetaobjectBySlug($artistSlug);
:large_blue_circle: I strongly recommend wrapping this one using `once()`:


```suggestion
                        $artist = once(function () use ($artistSlug) {
                            return $this->shopifyAdapter->getArtistMetaobjectBySlug($artistSlug);
                        });
```

That way, this part of code would be executed only once, and the results will be kept in memory.

For older versions of Laravel, you would have to put those in array cache, like this:

```php
cache()
    ->store('array')
    ->rememberForever('cache key', fn () => $this->shopify->getArtistMetaobjectBySlug('...'));
```

2024-08-27 16:34 UTC, radmen commented on app/Console/Commands/ProductsArtistsSync.php
> +                                    'type' => 'single_line_text_field',
:red_circle: This is not a correct type. It should be `metaobject_reference`

2024-08-27 16:43 UTC, ivancosmin commented on app/Console/Commands/ProductsArtistsSync.php
> +                        $artist = $this->shopifyAdapter->getArtistMetaobjectBySlug($artistSlug);
pushed the changes

2024-08-29 08:02 UTC, radmen approved these changes

2024-08-29 08:21 UTC, merged